services:
  - type: web
    name: workpermit-backend
    env: python
    plan: starter
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generate: secret
      - key: FRONTEND_URL
        value: "https://work-permit-system.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://work-permit-system.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://work-permit-system.vercel.app"
      - key: ALLOWED_HOSTS
        value: "work-permit.onrender.com"
      - key: AUTH_COOKIE_SAMESITE
        value: "None"
      - key: AUTH_COOKIE_SECURE
        value: "True"
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@workpermit.local"
