# Generated by Django 4.2.9 on 2026-04-20 10:55

import apps.permits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('form_data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.permits.models.permit_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permits_workpermit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='permits_wor_user_id_f866af_idx'), models.Index(fields=['serial_number'], name='permits_wor_serial__de3b36_idx')],
            },
        ),
    ]
