# Generated by Django 4.2.9 on 2026-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_workpermit_group_insurance_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvallog',
            new_name='permits_app_permit__ea0a6d_idx',
            old_name='permits_app_permit_idx',
        ),
        migrations.RenameIndex(
            model_name='approvallog',
            new_name='permits_app_stage_8f1567_idx',
            old_name='permits_app_stage_idx_2',
        ),
        migrations.RenameIndex(
            model_name='approver',
            new_name='permits_app_stage_0925e3_idx',
            old_name='permits_app_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='approver',
            new_name='permits_app_user_id_3dda2a_idx',
            old_name='permits_app_user_idx',
        ),
        migrations.RenameIndex(
            model_name='workpermit',
            new_name='permits_wor_status_e53d9a_idx',
            old_name='permits_wor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workpermit',
            new_name='permits_wor_current_8a2707_idx',
            old_name='permits_wor_current_idx',
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Reinitiated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('stage_1', 'Pending Stage 1 Review'), ('stage_1_rejected', 'Reinitiated at Stage 1'), ('stage_2', 'Pending Stage 2 Review'), ('stage_2_rejected', 'Reinitiated at Stage 2'), ('approved', 'Approved'), ('cancelled', 'Cancelled by Employee')], default='draft', max_length=20),
        ),
    ]
